module.exports = {
checkEmail:"Email is already taken.",
CHKFIELD:"Please check all fields.",
adminRegister:"Admin registration successfully.",
adminLogin:"Login successfully.",
passIncurrect:"Password incorrect.",
Nodata:"No data found.",
updatedEmp:"Update details of employee.",
checkAllField:"Check all fields.",
blockEmp:"Block employee successfully.",
deleteEmp:"Delete employee successfully.",
getAllEmp:"Get all employees.",
addEmp:"Add employee successfully.",
addVend:"Add vendor successfully.",
getAllVend:"Get all vendor.",
deleteVend:"Delete vendor successfully.",
updateVend:"Update details of vendor.",
blockVend:"Block vendor successfully.",
getAllLeaves:"Get all leaves.",
addApplyLeave:"Apply leave successfully.",
allPriest:"Get all priest.",
allPujaAtTemple:"Get all pujaAtTemple.",
allPujaAtHome:"Get all pujaAtHome.",
addPriestBooking:"Add priest booking successfully.",
addFacilityBooking:"Add facility booking successfully.",
allFacility:"Get all facility.",
getAllBookingData:"Get all priest and facility booking.",
allUnits:"Get all units.",
allTemplates:"Get all templates.",
allItems:"Get all items.",
allCodes:"Get all expense and committee codes.",
allDelivery:"Get all delivery.",
purchaseOrder:"Your order is done.",
getAllPurchasOrder:"Get all purchase order.",
addCulturalPayments:"Add cultural payments details.",
allCheck:"Get all check payable.",
allOfficers:"Get all officers.",
allPaymentMode:"Get all payment mode.",
NoData:"No data found.",
allCostCenter:"Get all cost center.",
allPoStatus:"Get all po status.",
addRecievedItems:"Add recieved items.",
poId:"Po_number is incorrect.",
approved_1_by:"Approved by officers.",
approved_2_by:"Approved by officers.",
checkFields:"Check all fields.",
addPoInvoice:"Add po invoice.",
allDeity:"Get all diety.",
invoiceModule:"Get invoice details.",
PriestRservationAtHome:"Priest reservation at home .",
getAllDays:"Get all days.",
templeSchedule:"Priest reservation at temple .",
MSGUPDATEDPASSWORD:"This is new password.",
FORGETPASS1:"Forget password successfully.Please check email you got new password.",
NOEMAIL:"Email is not exists.",
NonPoInvoice:"Added non po invoice details. ",
getAllPurchasData:"Get all purchase order info.",
getPujaFees:"Get puja fee.",
allPuja:"Get all puja.",
gettimefee:"Get all facility time and fee.",
addInvoice:"Add invoice of priest bookings."
};